### PR TITLE
Fix docker context calculation re: .dockerignore

### LINKED ISSUE #576: .dockerignore support seems broken
I am finding that my docker context includes many directories that are listed in the `.dockerignore`.  It also seems unable to handle entries that start with `!` -- instead, it tries to ignore a file that literally starts with this character.

https://docs.docker.com/engine/reference/builder/#dockerignore-file

### PR DESCRIPTION
**Pull request by ianfixes**
* Fixes #576 

This patch implements the logic described [in the Dockerfile reference for `.dockerignore`](https://docs.docker.com/engine/reference/builder/#dockerignore-file).

> Lines starting with `!` (exclamation mark) can be used to make exceptions to exclusions. The following is an example `.dockerignore` file that uses this mechanism:
> ```
> *.md
> !README.md
> ```
> All markdown files except `README.md` are excluded from the context.
> 
> The placement of ! exception rules influences the behavior: the last line of the `.dockerignore` that matches a particular file determines whether it is included or excluded. Consider the following example:
> 
> ```
> *.md
> !README*.md
> README-secret.md
> ```
> 
> No markdown files are included in the context except `README` files other than`README-secret.md`.

### CODE REVIEW

**Comment by ianfixes** [comment]
@tlunter could you please approve running workflows on this PR so that I can get CI results?

**Comment by ianfixes** [comment]
@nylkotuby could you please approve running workflows on this PR so that I can get CI results?

**Comment by nylkotuby** [comment]
@ianfixes I'm no longer a maintainer on this repository, sorry!

**Comment by ls-todd-lunter** [comment]
@ianfixes approved. Sorry, we've migrated accounts over here so I missed the tag.

**Comment by ianfixes** [comment]
Thanks to both of you!  

Also, small world: Todd I think when I toured Upserve you showed me your Amtrak status tool!

**Comment by ianfixes** [comment]
I think I need the approval one more time.  There must be some approval tied to a commit that goes away if I force-push my branch.  Added unit tests and fixed the ABC complexity issue.

**Comment by ianfixes** [comment]
All tests are now passing, I look forward to any review comments

**Comment by ianfixes** [comment]
@tlunter can I get a second approval here?

**Comment by ianfixes** [comment]
What timeline am I looking at for having this reviewed and (hopefully) released?  This is an honest question, not an expression of urgency -- my team is just trying to plan around it.

File: lib/docker/util.rb [hunk 1]
```diff
@@ -259,21 +284,22 @@ def build_config_header(credentials)
...
+      acc.merge(File.directory?(f) ? glob_all_files("#{f}/**/*") : [f])
+    end
   end
 
-  def remove_ignored_files!(directory, files)
-    ignore = File.join(directory, '.dockerignore')
-    return unless files.include?(ignore)
-    ignored_files(directory, ignore).each { |f| files.delete(f) }
+  def glob_all_files(pattern)
+    (Dir.glob(pattern, File::FNM_DOTMATCH) - ['..', '.']).reject { |p| p.end_with?("/.") }
```
Comment (ls-todd-lunter) [inline lib/docker/util.rb:302]: Is the change for this function needed? Specifically the reject for lines ending in `/.`. Just wondering when this would happen.

File: lib/docker/util.rb [hunk 2]
```diff
@@ -142,10 +144,33 @@ def create_dir_tar(directory)
...
+  # return the set of files that form the docker context
+  # implement this logic https://docs.docker.com/engine/reference/builder/#dockerignore-file
+  def docker_context(directory)
+    all_files = glob_all_files(File.join(directory, "**/*"))
+    dockerignore = File.join(directory, '.dockerignore')
+    return all_files unless all_files.include?(dockerignore)
+
+    # iterate over non-comments and non-blanks from the dockerignore file,
+    # starting with the initial glob as working set
+    File.read(dockerignore).each_line.map(&:strip)
```
Comment (ls-todd-lunter) [inline lib/docker/util.rb:157]: Can we move each of these to new lines? Would prefer if we're chaining vertically, to chain it all that way.

File: lib/docker/util.rb (hunk 1 above)
Comment (ianfixes) [reply lib/docker/util.rb:302]: Sure -- just added some debugging lines to find out where this happens.  

For a glob of `/Users/ianfixes/Development/docker-api/spec/docker/../fixtures/top/**/*`, one of the returned values is `/Users/ianfixes/Development/docker-api/spec/docker/../fixtures/top/.`

File: lib/docker/util.rb [hunk 3]
```diff
@@ -1,8 +1,10 @@
+require 'set'
+
 # This module holds shared logic that doesn't really belong anywhere else in the
 # gem.
 module Docker::Util
   # http://www.tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm#STANDARD-WILDCARDS
-  GLOB_WILDCARDS = /[\?\*\[\{]/
+  GLOB_WILDCARDS = /[\?\*\[\{\]\}]/
```
Comment (ianfixes) [inline lib/docker/util.rb:7]: This is no longer used anywhere (I factored out the need for it while reducing ABC complexity), but I wasn't sure whether to delete it

Comment (ls-todd-lunter) [reply lib/docker/util.rb:7]: That makes sense. Let's leave it, but maybe we can add a comment that it's unused now?

File: lib/docker/util.rb [hunk 4]
```diff
@@ -259,21 +286,23 @@ def build_config_header(credentials)
     }
   end
 
-  def glob_all_files(pattern)
-    Dir.glob(pattern, File::FNM_DOTMATCH) - ['..', '.']
+  # do a directory glob that matches .dockerignore behavior
+  # specifically: matched directories are considered a recursive match
+  def dockerignore_compatible_glob(pattern)
+    begin
+      some_dirs, some_files = glob_all_files(pattern).partition { |f| File.directory?(f) }
```
Comment (ls-todd-lunter) [inline lib/docker/util.rb:293]: I tried to see if we can use `File.fnmatch?` instead of needing to re-glob each time, but apparently the rules for that don't work. `x/**/y` doesn't match `x/y` while it does for `Dir.glob`... That's regardless of the flags passed to `fnmatch?` as well.

Comment (ianfixes) [reply lib/docker/util.rb:293]: Does that mean some action is necessary here?  Am I missing a test case?

Comment (ls-todd-lunter) [reply lib/docker/util.rb:293]: Sorry, nope, was just sharing another avenue that doesn't seem possible right now.

**Comment by ls-todd-lunter** [comment]
Released in v2.2.0.

**Comment by ianfixes** [comment]
Awesome, thank you!
