### PR TITLE
Automatically retry with correct content-type

### LINKED ISSUE #568: The connection content_type should be modified based on the type of operation occuring
I was attempting to use this gem with `podman` and I'm not sure if it has more strict content type checks than docker, but the default that sets `application/json` appears to be incorrect for various operations based on the [API docs](https://docs.docker.com/engine/api/v1.41/).

https://github.com/swipely/docker-api/blob/1e9b9cc5f0f38dcd54c18189812328bb802d3656/lib/docker/connection.rb#L79

### PR DESCRIPTION
**Pull request by trevor-vaughan**
The podman socket will return a note about the correct content-type that
should be used for a given type of message if it is incorrect.

This is a workaround to automatically correct the content-type and
resubmit the call.

A full correction would be to update all of the different connection
entries but this appears to work correctly in the short term.

Fixes #568

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
The errors in Travis appear to be related to the busybox image and not the code changes as far as I can tell.

**Comment by trevor-vaughan** [comment]
Ok, so the Travis tests are failing (for whatever reason), but everything [passes in GitHub Actions](https://github.com/trevor-vaughan/docker-api/runs/1802694288?check_suite_focus=true) which I added to this PR to see if it would help.

**Comment by trevor-vaughan** [comment]
Sorry folks, the different ruby versions are being troublesome. Will update again once I have the GitHub Actions working properly.

**Comment by trevor-vaughan** [comment]
Ok, this is now [correctly passing in GitHub Actions](https://github.com/trevor-vaughan/docker-api/actions/runs/527867238) and should be ready for review.

**Comment by trevor-vaughan** [comment]
@phaelyn @tlunter Hi folks. Sorry for the bother, but I just wanted to check and see if you're still maintaining the gem and/or open to contributions. The PR list seems pretty extensive and hasn't really shifted much from what I can tell.

**Comment by tlunter** [comment]
@trevor-vaughan can i ask why you decided to add github actions to the PR? we are already using travis for the testing of the repo.

**Comment by trevor-vaughan** [comment]
@tlunter Well, the main reason is that I couldn't get them to work in Travis. I (and everyone else at this point) can guarantee that they will be run in GitHub. Once I did the work, I figured I should go ahead and submit it.

Also, I'm not sure if you were hit by this (yet) but Travis' support of FOSS projects is now severely lacking with no apparent exit plan.

If you don't like it, I can certainly back it out, but it works quite well (particularly for contributors).

File: lib/docker/image.rb [hunk 1]
```diff
@@ -227,7 +227,16 @@ def search(query = {}, connection = Docker.connection, creds = nil)
     # Import an Image from the output of Docker::Container#export. The first
     # argument may either be a File or URI.
     def import(imp, opts = {}, conn = Docker.connection)
-      open(imp) do |io|
+      require 'open-uri'
+
+      # This differs after Ruby 2.4
+      if URI.public_methods.include?(:open)
```
Comment (tlunter) [inline lib/docker/image.rb:233]: Is this just `#respond_to?`?

File: lib/docker/image.rb [hunk 2]
```diff
@@ -227,7 +227,16 @@ def search(query = {}, connection = Docker.connection, creds = nil)
     # Import an Image from the output of Docker::Container#export. The first
     # argument may either be a File or URI.
     def import(imp, opts = {}, conn = Docker.connection)
-      open(imp) do |io|
+      require 'open-uri'
```
Comment (tlunter) [inline lib/docker/image.rb:230]: I don't frequently open IO objects beside local files, what's the benefit here vs the prior `open` method?

File: lib/docker/image.rb (hunk 1 above)
Comment (trevor-vaughan) [reply lib/docker/image.rb:233]: It's not actually. It `respond_to?` returns true in both pre 2.4 and post 2.4 so we need to check and see if it's an actual public method.

File: lib/docker/image.rb (hunk 2 above)
Comment (trevor-vaughan) [reply lib/docker/image.rb:230]: Seamless Ruby 2.7 compatibility.

File: lib/docker/connection.rb [hunk 3]
```diff
@@ -35,21 +35,51 @@ def resource
...
+          # This is not perfect since it relies on processing a message that
+          # could change in the future. However, it should be a good stop-gap
+          # until all methods are updated to pass in the appropriate content
+          # type.
+          #
+          # A current example message is:
+          #   * 'Content-Type: application/json is not supported. Should be "application/x-tar"'
+          matches = response_cause.delete('"\'').scan(%r{(application/\S+)})
+          unless matches.count < 2
+            request[:headers]['Content-Type'] = matches.last.first
```
Comment (tlunter) [inline lib/docker/connection.rb:65]: This is pretty spooky to me. Can we log something so that folks can clearly open an issue or something when this is hit? Also, is there a particular endpoint that you know needs to be fixed?

**Comment by tlunter** [comment]
I'd prefer we used the travis-ci stuff. There is a couple tests that run with the config there that's hidden. Agreed that we will probably need to migrate soon though, so even putting in another PR with the travis stuff removed and the actions stuff added would help.

File: lib/docker/connection.rb (hunk 3 above)
Comment (trevor-vaughan) [reply lib/docker/connection.rb:65]: Not going to lie, it's 100% spooky. I'm fine with logging things if you have a preferred logging mechanism. I allowed updates from maintainers so feel free to hack away if that's easier and I can put it back through its paces in podman.

I took a swipe at the Docker API docs but multiple endpoints need to be updated and the downstream code doesn't actually support passing it in as an option.

As the comment mentions, this is basically a stop-gap until the real fix can be introduced later (which will probably involve a larger code overhaul if I'm reading things right).

**Comment by trevor-vaughan** [comment]
@tlunter Would you also be OK with just leaving it and re-adding the travis stuff? You can change what you pay attention to in the project settings.

I literally couldn't get anything to run in Travis so I'd have to ping-pong it back and forth to figure out if it's still working.

File: lib/docker/connection.rb (hunk 3 above)
Comment (tlunter) [reply lib/docker/connection.rb:65]: I guess the limited ability for logging is from: https://github.com/swipely/docker-api/pull/569/files#diff-a8fbee6483c191f77ba681f51094f68035815545d435d51a195934263bd79850R86-R90

Doesn't really offer much since it's opt in...

**Comment by trevor-vaughan** [comment]
@tlunter Do you prefer lots of little pushes with a merge/squash at the end or rebase with force push?

File: lib/docker/connection.rb (hunk 3 above)
Comment (trevor-vaughan) [reply lib/docker/connection.rb:65]: Also, while this is spooky, it's "safe spooky" in that the worst case scenario is that the thing you were trying to do gets tried twice and doesn't work (and returns the usual error).

**Comment by tlunter** [comment]
The former, typically with a standard merge, no squash. Would prefer squashing only when pushing to test something. Those can merged/rebased together.

File: lib/docker/connection.rb (hunk 3 above)
Comment (tlunter) [reply lib/docker/connection.rb:65]: My fear mostly stems from the docker engine API being a bit harder to work with earlier on and potentially performing destructive behaviors, but not returning the right result. Agreed that it shouldn't actually do that here since it's failing at the API top-level.

**Comment by trevor-vaughan** [comment]
OK, this obviously isn't making anyone's life hard but mine right now so I can fix things up this weekend if you're good with the general implementation.

I can split the github stuff into a separate commit as well if you'd like so it gets separated away from the actual code update.

**Comment by tlunter** [comment]
That would be appreciated. We had done some work to fix the `busybox` issue in travis towards the end of last year, and now it's back... Going to see if I can dig up what our theory was there.

File: lib/docker/connection.rb (hunk 3 above)
Comment (trevor-vaughan) [reply lib/docker/connection.rb:65]: Well, `docker` doesn't care. It seems to just ignore it and "do the right thing" for the operation. The `podman` API is strict and will fail.

**Comment by trevor-vaughan** [comment]
@tlunter Everything appears to be good to go now.

I went ahead and updated the rest of the tests to work with Podman and added podman tests to the GitHub Actions.

File: lib/docker.rb [hunk 4]
```diff
@@ -119,6 +119,20 @@ def ping(connection = self.connection)
     connection.get('/_ping')
   end
 
+  # Determine if the server is podman or docker.
+  def podman?(connection = self.connection)
```
Comment (tlunter) [inline lib/docker.rb:123]: I wonder if we can instead cache this value on the connection. Right now we're going to perform this check every time we perform certain requests, which makes another API call to the version endpoint. A connection certainly isn't guaranteed to be fixed to a single docker endpoint, but that would mean swapping the daemon listening on the socket out from underneath the client, which would be a pretty odd thing to do...

Comment (trevor-vaughan) [reply lib/docker.rb:123]: @tlunter I'm certainly fine with that. Some people don't care for instance variables popping up everywhere but happy to do that if you'd like.

I agree that it would be super weird to swap it out in the middle of a program.

Comment (tlunter) [reply lib/docker.rb:123]: Yes please. Otherwise everything else looks good to me.

**Comment by trevor-vaughan** [comment]
@tlunter Should be good to go. You might want to consider adding some of the other items in there as well. Things like `version()` and `info()` are good candidates.

**Comment by trevor-vaughan** [comment]
@tlunter So, I seem to be getting some `cane` issues but I didn't touch anything that it's referring to. Should I just bump up the values? I didn't see any way to do line-by-line exclusions like you can in `rubocop`.

**Comment by tlunter** [comment]
@trevor-vaughan I don't actually know where to look for the failures you're seeing since I only see travis on this PR, but yea, can just increase the limit for cane for now.

**Comment by trevor-vaughan** [comment]
@tlunter Sorry about the flipping. Everything looks good now though. https://github.com/trevor-vaughan/docker-api/actions/runs/591109632

**Comment by trevor-vaughan** [comment]
@tlunter Does this work for you now or did I miss something (pretty sure I got it all)?

File: lib/docker.rb [hunk 5]
```diff
@@ -119,6 +119,29 @@ def ping(connection = self.connection)
...
+    @attrs ||= {}
```
Comment (tlunter) [inline lib/docker.rb:124]: Sorry, I was thinking we could cache the `version` request coming from the connection. This is caching it on the top level module right now which can be shared across many connections.

File: lib/docker.rb [hunk 6]
```diff
@@ -119,6 +119,29 @@ def ping(connection = self.connection)
...
+      Array(version(connection)['Components']).find do |component|
+        component['Name'] && component['Name'].include?('Podman')
+      end
+    ).nil?
+
+    @attrs[:podman]
+  end
+
+  # Determine if the session is rootless.
+  def rootless?(connection = self.connection)
```
Comment (tlunter) [inline lib/docker.rb:137]: Since this isn't used programmatically for other API calls, we can keep this one uncached.

File: lib/docker.rb (hunk 5 above)
Comment (tlunter) [reply lib/docker.rb:124]: https://github.com/trevor-vaughan/docker-api/compare/podman-compat...swipely:podman-compat-cache-version Like this.

File: lib/docker.rb (hunk 6 above)
Comment (trevor-vaughan) [reply lib/docker.rb:137]: I've ended up needing to use it quite a bit elsewhere so it makes sense to cache it to me.

**Comment by trevor-vaughan** [comment]
@tlunter Well, in theory this is caching in the connection, not globally, across the board now. Unfortunately, I'm having a bit of fun with GitHub Actions not being able to decide which version of Ubuntu it wants to provide at the moment. The tests [worked fine in my branch](https://github.com/trevor-vaughan/docker-api/actions/runs/606568212).

File: .github/workflows/unit_test.yml [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+        run: |
+          set -x
+          sudo apt-get remove -y docker docker-engine docker.io containerd runc ||:
+          sudo apt-get update -y
+          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
+          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+          sudo apt-get update -y
+          sudo apt-cache gencaches
+          sudo apt-get install -y docker-ce=$( apt-cache madison docker-ce | grep -e $DOCKER_VERSION | cut -f 2 -d '|' | head -1 | sed 's/\s//g' )
```
Comment (tlunter) [inline .github/workflows/unit_test.yml:48]: Maybe we can also grep here based on `lsb_release`? Are we expecting it to be `bionic` or `focal`? I assume `bionic` because of the `runs-on` for the `docker-rspec` section.

Comment (trevor-vaughan) [reply .github/workflows/unit_test.yml:48]: The repo setup on Line 45 targets it for whatever it's running. Installation outside of that  won't work.

`ubuntu-latest` seemed to give me varying results so I just gave up and queried whatever I had.

Comment (trevor-vaughan) [reply .github/workflows/unit_test.yml:48]: @tlunter I think this should be OK if the message from yesterday made sense :point_up:

Comment (tlunter) [reply .github/workflows/unit_test.yml:48]: Oh yes, definitely. Didn't see this was after the change that made the CI tests pass again. Thanks for resolving.

**Comment by trevor-vaughan** [comment]
@tlunter Awesome! Is there anything else you need me to do before a merge (and hopefully release) is possible?

**Comment by tlunter** [comment]
Released as v2.1.0. Thanks a lot @trevor-vaughan

**Comment by trevor-vaughan** [comment]
@tlunter Thanks for putting up with all the noise and working it through with me!
